In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris


In [2]:
irisModule = load_iris()
dataset = np.array(irisModule.data)

In [5]:
covarianceMatrix = pd.DataFrame(data = np.cov(dataset, rowvar = False),
                                columns = irisModule.feature_names, 
                                index = irisModule.feature_names)
covarianceMatrix

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           0.685694         -0.042434           1.274315   
sepal width (cm)           -0.042434          0.189979          -0.329656   
petal length (cm)           1.274315         -0.329656           3.116278   
petal width (cm)            0.516271         -0.121639           1.295609   

                   petal width (cm)  
sepal length (cm)          0.516271  
sepal width (cm)          -0.121639  
petal length (cm)          1.295609  
petal width (cm)           0.581006

In [6]:
eigenvalues, eigenvectors = np.linalg.eig(covarianceMatrix)
print("eigenvalues:\n{}\neigenvectors:\n{}".format(eigenvalues, eigenvectors))

eigenvalues:
[4.22824171 0.24267075 0.0782095  0.02383509]
eigenvectors:
[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]


In [25]:
np.dot(covarianceMatrix.values[:, :], eigenvectors[:, 0])

array([ 1.52802986, -0.35738162,  3.62221038,  1.51493333])

In [17]:
eigenvalues[0] * eigenvectors[:, 0]

array([ 1.52802986, -0.35738162,  3.62221038,  1.51493333])

In [28]:
covarianceMatrix.values[:, :] * eigenvectors[:, 0]

array([[ 0.24780044,  0.00358663,  1.09166858,  0.18497421],
       [-0.01533508, -0.01605754, -0.28240693, -0.04358207],
       [ 0.46052051,  0.02786339,  2.66962364,  0.46420285],
       [ 0.18657331,  0.01028127,  1.10991049,  0.20816827]])

In [ ]:
featureVector = eigenvectors[:,:2]
featureVectorTranspose = np.transpose(featureVector)
datasetTranspose = np.transpose(dataset)
newDatasetTranspose = np.matmul(featureVectorTranspose, datasetTranspose)
newDataset = np.transpose(newDatasetTranspose)